server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Redirect routing internal React ke index.html
        try_files $uri $uri/ /index.html;
    }

    # Cache asset statik
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000";
    }
}
